services:
  weather-fetcher:
    build: .
    environment:
      - HOME_ASSISTANT_TOKEN=${HOME_ASSISTANT_TOKEN}
      - HOME_ASSISTANT_SENSOR_TEMPERATURE=${HOME_ASSISTANT_SENSOR_TEMPERATURE}
      - HOME_ASSISTANT_API_BASE=${HOME_ASSISTANT_API_BASE}
      - HOME_ASSISTANT_SENSOR_HUMIDITY=${HOME_ASSISTANT_SENSOR_HUMIDITY}
      - LOADER_MODE=continuous
      - PYTHONUNBUFFERED=1
    volumes:
      - weather_data3:/app/data
    command: ["uv", "run", "python", "-u", "src/loader.py"]
    restart: unless-stopped

  weather-webserver:
    build: .
    environment:
      - FLASK_PORT=3300
      - PYTHONUNBUFFERED=1
    volumes:
      - weather_data3:/app/data
    ports:
      - "3300:3300"
    command: ["uv", "run", "python", "-u", "src/webserver.py"]
    restart: unless-stopped

volumes:
  weather_data3:
