services:
  weather-app:
    build: .
    environment:
      - MODE=both
      - HOME_ASSISTANT_TOKEN=${HOME_ASSISTANT_TOKEN}
      - HOME_ASSISTANT_SENSOR_TEMPERATURE=${HOME_ASSISTANT_SENSOR_TEMPERATURE}
      - HOME_ASSISTANT_API_BASE=${HOME_ASSISTANT_API_BASE}
      - HOME_ASSISTANT_SENSOR_HUMIDITY=${HOME_ASSISTANT_SENSOR_HUMIDITY}
      - FLASK_PORT=3300
    volumes:
      - weather_data:/app/data
    ports:
      - "3300:3300"
    restart: unless-stopped

volumes:
  weather_data:
